title: SÃ¼leyman Topdemir
logo: /assets/img/st.png
description: #text below the image
  First Description
  <br><br>
  Second Description
  <br><br>
  <a href="https://www.linkedin.com/in/stopdemir/">My Linkedin<a>
show_downloads: false
theme: jekyll-theme-minimal
