title: Süleyman Topdemir
logo: /assets/img/st2.png
description: stopdemir@stopdemir.com
  <p><p>
    <a href="https://www.linkedin.com/in/stopdemir">
      <img src="https://custom-icon-badges.demolab.com/badge/LinkedIn-0A66C2?style=for-the-badge&logo=linkedin-white&logoColor=white" alt="Go to my Linkedin Profile">
    </a>
    <a href="https://www.github.com/stopdemir">
      <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="Go to my GitHub Profile">
    </a>
    <a href="https://www.kaggle.com/stopdemir">
      <img src="https://img.shields.io/badge/Kaggle-20BEFF?style=for-the-badge&logo=Kaggle&logoColor=white" alt="Go to my Kaggle Profile">
    </a>
    <a href="https://www.upwork.com/freelancers/~0139852018699c805e">
      <img src="https://img.shields.io/badge/UpWork-6FDA44?style=for-the-badge&logo=Upwork&logoColor=white" alt="Go to my Upwork Profile">
    </a>
    <a href="https://www.fiverr.com/s/VY6Z3vz">
      <img src="https://img.shields.io/badge/Fiverr-1DBF73?style=for-the-badge&logo=fiverr&logoColor=white" alt="Go to my Fiverr Profile">
    </a>
    <a href="https://stackoverflow.com/users/18382448/süleyman-topdemir">
      <img src="https://img.shields.io/badge/-Stackoverflow-FE7A16?style=for-the-badge&logo=stack-overflow&logoColor=white" alt="Go to my Stackoverflow Profile">
    </a>
  </p></p>

theme: jekyll-theme-minimal