title: SÃ¼leyman Topdemir
logo: /assets/img/st2.png
description: #Data Scientist | Machine Learning Engineer | AI Enthusiast 
  <p><p>
    <img src="https://img.shields.io/badge/stopdemir@stopdemir.com-D14836?logo=gmail&logoColor=white">
    <a href="https://www.linkedin.com/in/stopdemir">
      <img src="https://custom-icon-badges.demolab.com/badge/LinkedIn-0A66C2?logo=linkedin-white&logoColor=fff" alt="Go to my Linkedin Profile">
    </a>
    <a href="https://www.github.com/stopdemir">
      <img src="https://img.shields.io/badge/GitHub-%23121011.svg?logo=github&logoColor=white" alt="Go to my GitHub Profile">
    </a>
    <a href="https://www.kaggle.com/stopdemir">
      <img src="https://img.shields.io/badge/Kaggle-20BEFF?logo=kaggle&logoColor=fff" alt="Go to my Kaggle Profile">
    </a>
    <a href="https://www.upwork.com/freelancers/~0139852018699c805e">
      <img src="https://img.shields.io/badge/Upwork-6FDA44?logo=upwork&logoColor=fff" alt="Go to my Upwork Profile">
    </a>
    <a href="https://www.fiverr.com/s/VY6Z3vz">
      <img src="https://img.shields.io/badge/Fiverr-1DBF73?logo=fiverr&logoColor=fff" alt="Go to my Fiverr Profile">
    </a>
  </p></p>

theme: jekyll-theme-minimal