title: SÃ¼leyman Topdemir
logo: /assets/img/st.png
description: #text below the image
  <p><p align="center"> 
  <a href="https://linkedin.com/in/stopdemir">LinkedIn</a> |
  <a href="https://github.com/stopdemir">GitHub</a> </p>

theme: jekyll-theme-minimal
